name: CICD

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t kithminasiriwardana13/ms-property-listings-api .
      - name: Publish image to docker hub
        run: docker push kithminasiriwardana13/ms-property-listings-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull kithminasiriwardana13/ms-property-listings-api:latest
      - name: Delete old container
        run: docker rm -f ms-property-listings-api-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name ms-property-listings-api-container kithminasiriwardana13/ms-property-listings-api
